apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-db-init
  namespace: orders
data:
  init-db.sh: |-
    #!/bin/bash
    set -e
    
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      SELECT 'CREATE DATABASE orders' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'orders');
    EOSQL