apiVersion: batch/v1
kind: Job
metadata:
  name: orders-migration
  namespace: orders
spec:
  template:
    spec:
      containers:
      - name: migration
        image: 131793876715.dkr.ecr.us-east-1.amazonaws.com/microservices/orders
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: orders-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orders-secret
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: orders-secret
              key: postgres-db
        - name: DATABASE_URL
          value: postgresql+psycopg://postgres:postgres@orders-postgres:5432/orders
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        command: ["alembic", "upgrade", "head"]
      restartPolicy: OnFailure