apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-app
  namespace: tech-namespace
  labels:
    app: tech-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-app
  template:
    metadata:
      labels:
        app: tech-app
    spec:
      containers:
      - name: tech-app
        image: 264591339294.dkr.ecr.us-east-1.amazonaws.com/tech-challenge:latest
        startupProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 12
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 20
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: tech-app-config
              key: DATABASE_URL