#version: "3.8"
#services:
#  migration:
#    build: .
#    environment:
#      DATABASE_URL: postgresql+psycopg://postgres:postgres@tech-database-2-dev.cdpoovnehujg.us-east-1.rds.amazonaws.com:5432/postgres
#    command: alembic upgrade head
#    depends_on:
#      - tech_app
#
#  tech_app:
#    build: .
#    ports:
#      - "8000:8000"
#    volumes:
#      - ./:/app
#    environment:
#      DATABASE_URL: postgresql+psycopg://postgres:postgres@tech-database-2-dev.cdpoovnehujg.us-east-1.rds.amazonaws.com:5432/postgres
#    command: uvicorn tech.api.app:app --host 0.0.0.0 --port 8000 --reload
#
